#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
from geometry_msgs.msg	import PoseStamped as ROS_Pose
import time

## ROS conversion
def talker():
    pub = rospy.Publisher('modelNI2R/pose', ROS_Pose, queue_size=10)
    posX = 0.0
    while not rospy.is_shutdown():
	Msg = ROS_Pose()
	posX += 1
	Msg.pose.position.x = posX
	pub.publish(Msg)
        rate.sleep()

## Programme principal
def main():
	talker()

if __name__ == '__main__':
	try:
		rospy.init_node('template_pub', anonymous=True)
		rate = rospy.Rate(10)
		main()
		rospy.spin()
	except rospy.ROSInterruptException:
		pass
